INSERT INTO appleDB.product (model, category, release_date) VALUES('iPhone 15', 'Smartphone', '2023-09-01');
INSERT INTO appleDB.product (model, category, release_date) VALUES('iPhone 15 Plus', 'Smartphone', '2023-09-01');
INSERT INTO appleDB.product (model, category, release_date) VALUES('iPhone 15 Pro', 'Smartphone', '2023-09-01');
INSERT INTO appleDB.product (model, category, release_date) VALUES('iPhone 15 Pro Max', 'Smartphone', '2023-09-01');
INSERT INTO appleDB.product (model, category, release_date) VALUES('iPhone 14', 'Smartphone', '2022-09-01');
INSERT INTO appleDB.product (model, category, release_date) VALUES('iPhone 14 Plus', 'Smartphone', '2022-09-01');
INSERT INTO appleDB.product (model, category, release_date) VALUES('iPhone 14 Pro', 'Smartphone', '2022-09-01');
INSERT INTO appleDB.product (model, category, release_date) VALUES('iPhone 14 Pro Max', 'Smartphone', '2022-09-01');
INSERT INTO appleDB.product (model, category, release_date) VALUES('iPhone 13', 'Smartphone', '2021-09-01');
INSERT INTO appleDB.product (model, category, release_date) VALUES('iPhone 13 Mini', 'Smartphone', '2021-09-01');
INSERT INTO appleDB.product (model, category, release_date) VALUES('iPhone 13 Pro', 'Smartphone', '2021-09-01');
INSERT INTO appleDB.product (model, category, release_date) VALUES('iPhone 13 Pro Max', 'Smartphone', '2021-09-01');
INSERT INTO appleDB.product (model, category, release_date) VALUES('iPhone 12', 'Smartphone', '2020-10-23');
INSERT INTO appleDB.product (model, category, release_date) VALUES('iPhone 12 Mini', 'Smartphone', '2020-11-13');
INSERT INTO appleDB.product (model, category, release_date) VALUES('iPhone 12 Pro', 'Smartphone', '2020-10-23');
INSERT INTO appleDB.product (model, category, release_date) VALUES('iPhone 12 Pro Max', 'Smartphone', '2020-11-13');
INSERT INTO appleDB.product (model, category, release_date) VALUES('iPhone 11', 'Smartphone', '2019-09-20');
INSERT INTO appleDB.product (model, category, release_date) VALUES('iPhone 11 Pro', 'Smartphone', '2019-09-20');
INSERT INTO appleDB.product (model, category, release_date) VALUES('iPhone 11 Pro Max', 'Smartphone', '2019-09-20');
INSERT INTO appleDB.product (model, category, release_date) VALUES('iPhone XS', 'Smartphone', '2018-09-21');
INSERT INTO appleDB.product (model, category, release_date) VALUES('iPhone XS Max', 'Smartphone', '2018-09-21');
INSERT INTO appleDB.product (model, category, release_date) VALUES('iPhone XR', 'Smartphone', '2018-10-26');
INSERT INTO appleDB.product (model, category, release_date) VALUES('iPhone X', 'Smartphone', '2017-11-03');
INSERT INTO appleDB.product (model, category, release_date) VALUES('MacBook Air M1 13-inch', 'Laptop', '2020-11-17');
INSERT INTO appleDB.product (model, category, release_date) VALUES('MacBook Air M2 13-inch', 'Laptop', '2022-07-15');
INSERT INTO appleDB.product (model, category, release_date) VALUES('MacBook Pro M1 13-inch', 'Laptop', '2020-11-17');
INSERT INTO appleDB.product (model, category, release_date) VALUES('MacBook Pro M1 14-inch', 'Laptop', '2021-10-18');
INSERT INTO appleDB.product (model, category, release_date) VALUES('MacBook Pro M1 16-inch', 'Laptop', '2021-10-18');
INSERT INTO appleDB.product (model, category, release_date) VALUES('MacBook Pro M2 13-inch', 'Laptop', '2022-06-01');
INSERT INTO appleDB.product (model, category, release_date) VALUES('MacBook Pro M2 14-inch', 'Laptop', '2022-10-18');
INSERT INTO appleDB.product (model, category, release_date) VALUES('MacBook Pro M2 16-inch', 'Laptop', '2022-10-18');
INSERT INTO appleDB.product (model, category, release_date) VALUES('Apple Watch Ultra', 'Smartwatch', '2023-09-01');
INSERT INTO appleDB.product (model, category, release_date) VALUES('Apple Watch Series 9', 'Smartwatch', '2023-09-01');
INSERT INTO appleDB.product (model, category, release_date) VALUES('Apple Watch Series 8', 'Smartwatch', '2022-09-01');
INSERT INTO appleDB.product (model, category, release_date) VALUES('Apple Watch Series 7', 'Smartwatch', '2021-09-14');
INSERT INTO appleDB.product (model, category, release_date) VALUES('Apple Watch Series 6', 'Smartwatch', '2020-09-15');
INSERT INTO appleDB.product (model, category, release_date) VALUES('Apple Watch Series 5', 'Smartwatch', '2019-09-20');
INSERT INTO appleDB.product (model, category, release_date) VALUES('Apple Watch SE', 'Smartwatch', '2020-09-15');
INSERT INTO appleDB.product (model, category, release_date) VALUES('AirPods (1st generation)', 'Earbuds', '2016-12-13');
INSERT INTO appleDB.product (model, category, release_date) VALUES('AirPods (2nd generation)', 'Earbuds', '2019-03-20');
INSERT INTO appleDB.product (model, category, release_date) VALUES('AirPods (3rd generation)', 'Earbuds', '2021-10-18');
INSERT INTO appleDB.product (model, category, release_date) VALUES('AirPods Pro (1st generation)', 'Earbuds', '2019-10-30');
INSERT INTO appleDB.product (model, category, release_date) VALUES('AirPods Pro (2nd generation)', 'Earbuds', '2023-09-01');
INSERT INTO appleDB.product (model, category, release_date) VALUES('AirPods Max', 'Headphones', '2020-12-15');
INSERT INTO appleDB.product (model, category, release_date) VALUES('iPad Pro 12.9-inch 5th generation', 'Tablet', '2021-04-30');
INSERT INTO appleDB.product (model, category, release_date) VALUES('iPad Pro 11-inch 3rd generation', 'Tablet', '2021-04-30');
INSERT INTO appleDB.product (model, category, release_date) VALUES('iPad Air 4th generation', 'Tablet', '2020-09-15');
INSERT INTO appleDB.product (model, category, release_date) VALUES('iPad 9th generation', 'Tablet', '2021-09-14');
INSERT INTO appleDB.product (model, category, release_date) VALUES('iPad mini 6th generation', 'Tablet', '2021-09-14');
INSERT INTO appleDB.product (model, category, release_date) VALUES('iMac 24-inch M1', 'Desktop', '2021-04-30');
INSERT INTO appleDB.product (model, category, release_date) VALUES('iMac 27-inch 5K', 'Desktop', '2020-08-04');
INSERT INTO appleDB.product (model, category, release_date) VALUES('Mac mini M1', 'Desktop', '2020-11-17');
INSERT INTO appleDB.product (model, category, release_date) VALUES('Studio Display', 'Monitor', '2022-03-08');

INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(1, 'https://store.storeimages.cdn-apple.com/8756/as-images.apple.com/is/iphone-15-finish-select-202309-6-1inch-black?wid=5120&hei=2880&fmt=p-jpg&qlt=80&.v=1692923777911', 'iPhone 15 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(2, 'https://store.storeimages.cdn-apple.com/8756/as-images.apple.com/is/iphone-15-finish-select-202309-6-7inch-black?wid=5120&hei=2880&fmt=p-jpg&qlt=80&.v=1692923781972', 'iPhone 15 Plus 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(3, 'https://store.storeimages.cdn-apple.com/8756/as-images.apple.com/is/iphone-15-pro-finish-select-202309-6-1inch-naturaltitanium?wid=2560&hei=1440&fmt=p-jpg&qlt=80&.v=1692846363993', 'iPhone 15 Pro 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(4, 'https://store.storeimages.cdn-apple.com/8756/as-images.apple.com/is/iphone-15-pro-finish-select-202309-6-7inch-naturaltitanium?wid=2560&hei=1440&fmt=p-jpg&qlt=80&.v=1692845702708', 'iPhone 15 Pro Max 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(5, 'https://store.storeimages.cdn-apple.com/8756/as-images.apple.com/is/iphone-14-finish-select-202209-6-1inch-blue?wid=5120&hei=2880&fmt=p-jpg&qlt=80&.v=1661026582322', 'iPhone 14 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(6, 'https://store.storeimages.cdn-apple.com/8756/as-images.apple.com/is/iphone-14-finish-select-202209-6-7inch-product-red?wid=5120&hei=2880&fmt=p-jpg&qlt=80&.v=1661027939728', 'iPhone 14 Plus 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(7, 'https://www.tradeinn.com/f/13933/139331634/apple-iphone-14-pro-128gb-6.1.jpg', 'iPhone 14 Pro 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(8, 'https://www.tradeinn.com/f/13933/139331648/apple-iphone-14-pro-max-128gb-6.7.jpg', 'iPhone 14 Pro Max 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(9, 'https://store.storeimages.cdn-apple.com/8756/as-images.apple.com/is/iphone-13-finish-select-202207-starlight?wid=5120&hei=2880&fmt=p-jpg&qlt=80&.v=1693064001768', 'iPhone 13 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(10, 'https://thumbnail6.coupangcdn.com/thumbnails/remote/492x492ex/image/retail/images/2033031697418648-fefd9d41-f6bc-47dd-b77c-80519f36e962.jpg', 'iPhone 13 Mini 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(11, 'https://cdn.alloallo.media/catalog/product/apple/iphone/iphone-13-pro/iphone-13-pro-silver.jpg', 'iPhone 13 Pro 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(12, 'https://www.tradeinn.com/f/13835/138359427/apple-iphone-13-pro-max-128gb-6.7.jpg', 'iPhone 13 Pro Max 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(13, 'https://i5.walmartimages.com/seo/Straight-Talk-Apple-iPhone-12-64GB-Black-Prepaid-Smartphone-Locked-to-Straight-Talk_66b2853b-6cb5-4f20-b73a-b60b39b6de44.6b3bf83a920058a47342318925f1dc2b.jpeg', 'iPhone 12 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(14, 'https://image.lguplus.com/common/images/hphn/product/A2399-128/imge_cut/ushop_A2399-128_67_A.jpg', 'iPhone 12 Mini 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(15, 'https://www.tradeinn.com/f/13782/137821863/apple-iphone-12-pro-256gb-6.1.jpg', 'iPhone 12 Pro 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(16, 'https://www.tradeinn.com/f/13782/137821848/apple-iphone-12-pro-max-6gb-128gb-6.7.jpg', 'iPhone 12 Pro Max 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(17, 'https://powermaccenter.com/cdn/shop/files/A012000x2000_d4e56501-8a7f-46e5-bc63-59965f8161c6_823x.jpg?v=1692051393', 'iPhone 11 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(18, 'https://regen.pk/cdn/shop/products/iphone-11-pro-164716.jpg?v=1674906905&width=1346', 'iPhone 11 Pro 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(19, 'https://www.tradeinn.com/f/13745/137457968/apple-iphone-11-pro-max-256gb-6.5.jpg', 'iPhone 11 Pro Max 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(20, 'https://cdn.alloallo.media/catalog/product/apple/iphone/iphone-xs/iphone-xs-gold.jpg', 'iPhone XS 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(21, 'https://cdn.alloallo.media/catalog/product/apple/iphone/iphone-xs-max/iphone-xs-max-gold.jpg', 'iPhone XS Max 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(22, 'https://cdn.alloallo.media/catalog/product/apple/iphone/iphone-xr/iphone-xr-white.jpg', 'iPhone XR 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(23, 'https://cdn.alloallo.media/catalog/product/apple/iphone/iphone-x/iphone-x-space-gray.jpg', 'iPhone X 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(24, 'https://store.storeimages.cdn-apple.com/8756/as-images.apple.com/is/macbook-air-space-gray-select-201810?wid=904&hei=840&fmt=jpeg&qlt=90&.v=1664472289661', 'MacBook Air M1 13-inch 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(25, 'https://store.storeimages.cdn-apple.com/8756/as-images.apple.com/is/refurb-macbook-air-m2-midnight-202208?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1659114484307', 'MacBook Air M2 13-inch 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(26, 'https://www.custommacbd.com/cdn/shop/products/mbp-spacegray-gallery2-202011_GEO_US_95bc5e0a-7c79-4b01-a31c-12d86f5fc92c.jpg?v=1613635041', 'MacBook Pro M1 13-inch 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(27, 'https://store.storeimages.cdn-apple.com/8756/as-images.apple.com/is/refurb-mbp14-space-m1-2021_GEO_KR?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1638575264000', 'MacBook Pro M1 14-inch 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(28, 'https://store.storeimages.cdn-apple.com/8756/as-images.apple.com/is/refurb-mbp16-silver-m1-2021_AV1?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1643239769000', 'MacBook Pro M1 16-inch 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(29, 'https://store.storeimages.cdn-apple.com/8756/as-images.apple.com/is/refurb-mbp13-m2-spacegray-202208?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1659374923283', 'MacBook Pro M2 13-inch 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(30, 'https://www.bhphotovideo.com/cdn-cgi/image/format=auto,fit=scale-down,width=500,quality=95/https://www.bhphotovideo.com/images/images500x500/apple_mphe3ll_a_14_macbook_pro_with_1673965870_1746351.jpg', 'MacBook Pro M2 14-inch 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(31, 'https://beyondthebox.ph/cdn/shop/products/MACBOOKPRO16INCHM2PRO20231_COLOR-SPACEGREY_CAPACITY-ALL_700x.jpg?v=1677481097', 'MacBook Pro M2 16-inch 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(32, 'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/MT653_VW_34FR+watch-49-titanium-ultra2_VW_34FR+watch-face-49-ocean-ultra2_VW_34FR_GEO_KR?wid=5120&hei=3280&bgc=fafafa&trim=1&fmt=p-jpg&qlt=80&.v=VHdUV3VJeUQyYW5oUlVUN3ZHS1VsL3Z4OU1ucmxYekw5aGF6a2ZZcG9hazdPN2hFakIxbjdEcTdvSm41NlVxWjY4QUVCdUdBMlBPcFgrL3RBcVB1cmY5akxmSjBzTThIaWphQnAvU3pXTzBzUWxJVGRZSG0zSzBCSWpnNDV1UWJ2S1B4dHJnZWVOenUzMmROdk9lOEdvSk43K25VYm5JaE5XMFJ6MEt5SVUydE13ZlhvMEpDZW1JRkhPN0RCZ0xWV1A4WkJQQ3BvYXllL2FBdjdLS29NZz09', 'Apple Watch Ultra 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(33, 'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/MUHL2_VW_34FR+watch-case-45-aluminum-silver-nc-s9_VW_34FR+watch-face-45-aluminum-silver-s9_VW_34FR_WF_CO_GEO_KR?wid=5120&hei=3280&bgc=fafafa&trim=1&fmt=p-jpg&qlt=80&.v=UEpLMEpkTm0rUDZrUXpnREJCeEVrYWc4WVhrTUNGaFJqVEpXMnB1Zy83d3ZBUXVDSWtueGFFWmRtanJVdndvV3l2M3JFSzgxeU4xYVE5dnVNZmdENng0ei9FYzZxSEVsdVptY0xJV2JFeThFK0VwOUdLVWtzTXc2dDNHRmlIN2tHS3V1ZVp1a2dnVkdrLzF6aVNrU0poSHVBU21zb3FuTUxsTng3RGdWaU9OZFJCVXJ3bE5KOVh5OUdia3BCcE1ScUxiN3NiK2JGZWRDNnlMS29nRGswd1hsanB4eURGQXV2SzZ0LzVwZlpHRTJESUFYTTR5ZFB0WkhvM1hTVnIrbw', 'Apple Watch Series 9 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(34, 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/FNU93_AV1?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1675957552507', 'Apple Watch Series 8 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(35, 'https://www.apple.com/newsroom/images/product/watch/standard/Apple_watch-series7-availability_contour-face_10052021_carousel.jpg.large_2x.jpg', 'Apple Watch Series 7 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(36, 'https://www.apple.com/newsroom/images/product/watch/standard/Apple_watch-series-6-aluminum-blue-case_09152020_carousel.jpg.large_2x.jpg', 'Apple Watch Series 6 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(37, 'https://www.apple.com/newsroom/images/product/watch/standard/Apple_watch_series_5-midnight-blue-band-space-gray-aluminum-case-091019_carousel.jpg.large_2x.jpg', 'Apple Watch Series 5 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(38, 'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/MT3H3ref_VW_34FR+watch-case-44-aluminum-starlight-nc-se_VW_34FR+watch-face-44-aluminum-starlight-se_VW_34FR?wid=5120&hei=3280&bgc=fafafa&trim=1&fmt=p-jpg&qlt=80&.v=cWI2UDhGRGlKTnRSM2hVcjBmQ1duaWhSbVIzRFJTYlp1MEk4OWNDaTcvNktoaXQwYi9wRGFOV2FsZVA1S1dYc3U0MnNvUmFpbmpuWFJpcHZlcmRSWStaZ2w5b1pKd0dWNW8yN1VNZDdZMDFmSGlnNkpTM1NGVHN6YWcySEw0THd4cVNUNDJadDNVSmRncE9SalAvZ24wUVN3R3VxZWhYYXgwOHljYmZFMXBocmMyRTN3NCt6QkoxaUdRb0FBay9VYktGTHdENW9lYUFnak5pcy9ReEdDYitVd1NTQTM3UmZlcFMyUUhtajBOOUFTbk5vY3l1VDJCbGQ3QjJZZUd1bQ', 'Apple Watch SE 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(39, 'https://support.apple.com/library/APPLE/APPLECARE_ALLGEOS/SP750/SP750-airpods.jpeg', 'AirPods (1st generation) 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(40, 'https://i.namu.wiki/i/RZHVyg8xJ6mOrdj_NS3RNFg6MWkIbJinZng_x7hjvJkNSrXdiiaghySOov8zodpoiJsRKQbfNmFdNRnefLvLdwgLyhOV_-KGZLbAPz5PNwk9n2kqO11fcjvc4_WzavKBajuH-pxkAOFXM9dpzju8KQ.webp', 'AirPods (2nd generation) 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(41, 'https://store.storeimages.cdn-apple.com/8756/as-images.apple.com/is/MME73?wid=2000&hei=2000&fmt=jpeg&qlt=95&.v=1632861342000', 'AirPods (3rd generation) 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(42, 'https://i.namu.wiki/i/2veoQoDl7vHNrQ1O-GtfmMjDcGfugqjNm-Ln2dxhCgWIhhMlt159upJfcx-Z49epS94OP_WoX2BkSQ76u2l8QaV_YfAPZbLqmr5v9SSaqYtnBO547VYF_5ZwF_oaxxsDwpxVbmwXjfd-TQ5l0AK-pg.webp', 'AirPods Pro (1st generation) 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(43, 'https://store.storeimages.cdn-apple.com/8756/as-images.apple.com/is/MTJV3?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1694014871985', 'AirPods Pro (2nd generation) 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(44, 'https://store.storeimages.cdn-apple.com/8756/as-images.apple.com/is/airpods-max-hero-select-202011_FMT_WHH?wid=607&hei=556&fmt=jpeg&qlt=90&.v=1633623988000', 'AirPods Max 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(45, 'https://store.storeimages.cdn-apple.com/8756/as-images.apple.com/is/refurb-ipad-pro-12-wifi-spacegray-2021?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1674663706569', 'iPad Pro 12.9-inch 5th generation 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(46, 'https://store.storeimages.cdn-apple.com/8756/as-images.apple.com/is/refurb-ipad-pro-11-wifi-silver-2021?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1674663704665', 'iPad Pro 11-inch 3rd generation 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(47, 'https://store.storeimages.cdn-apple.com/8756/as-images.apple.com/is/refurb-ipad-air-wifi-spacegrey-2021?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1644268641678', 'iPad Air 4th generation 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(48, 'https://store.storeimages.cdn-apple.com/8756/as-images.apple.com/is/refurb-ipad-wifi-spacegray-2022?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1674684441752', 'iPad 9th generation 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(49, 'https://store.storeimages.cdn-apple.com/8756/as-images.apple.com/is/refurb-ipad-mini-wifi-purple-gallery-2022?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1674165789066', 'iPad mini 6th generation 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(50, 'https://mstatic2.e-himart.co.kr/contents/goods/00/14/74/44/22/0014744422__MJV93KHA__M_640_640.jpg', 'iMac 24-inch M1 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(51, 'https://m.applerent.co.kr/web/product/big/202205/9eae30d1f9a11d9a6f36aeef5c604270.jpg', 'iMac 27-inch 5K 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(52, 'https://store.storeimages.cdn-apple.com/8756/as-images.apple.com/is/mac-mini-hero-202301_FMT_WHH?wid=904&hei=840&fmt=jpeg&qlt=90&.v=1671503802341', 'Mac mini M1 이미지');
INSERT INTO appleDB.product_image (product_id, image_url, description) VALUES(53, 'https://store.storeimages.cdn-apple.com/8756/as-images.apple.com/is/studio-display-og-202203?wid=600&hei=315&fmt=jpeg&qlt=95&.v=1645125507093', 'Studio Display 이미지');

INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(1, 'A17 Bionic', '6GB', '128GB/256GB/512GB', '6.1-inch OLED', 'Various', '3200mAh', 'Dual 12MP Ultra Wide cameras', 'iOS 17');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(2, 'A17 Bionic', '6GB', '128GB/256GB/512GB', '6.7-inch OLED', 'Various', '3500mAh', 'Dual 12MP Ultra Wide cameras', 'iOS 17');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(3, 'A17 Bionic', '6GB', '128GB/256GB/512GB/1TB', '6.1-inch OLED', 'Various', '3200mAh', 'Triple 12MP Ultra Wide, Wide', 'iOS 17');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(4, 'A17 Bionic', '6GB', '128GB/256GB/512GB/1TB', '6.7-inch OLED', 'Various', '3600mAh', 'Triple 12MP Ultra Wide, Wide', 'iOS 17');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(5, 'A16 Bionic', '6GB', '128GB/256GB/512GB', '6.1-inch OLED', 'Various', '3100mAh', 'Dual 12MP Ultra Wide cameras', 'iOS 16');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(6, 'A16 Bionic', '6GB', '128GB/256GB/512GB', '6.7-inch OLED', 'Various', '3300mAh', 'Dual 12MP Ultra Wide cameras', 'iOS 16');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(7, 'A16 Bionic', '6GB', '128GB/256GB/512GB/1TB', '6.1-inch OLED', 'Various', '3100mAh', 'Triple 12MP Ultra Wide cameras', 'iOS 16');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(8, 'A16 Bionic', '6GB', '128GB/256GB/512GB/1TB', '6.7-inch OLED', 'Various', '3500mAh', 'Triple 12MP Ultra Wide cameras', 'iOS 16');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(9, 'A15 Bionic', '4GB', '64GB/128GB/256GB', '6.1-inch OLED', 'Various', '2815mAh', 'Dual 12MP Ultra Wide cameras', 'iOS 15');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(10, 'A15 Bionic', '4GB', '64GB/128GB/256GB', '5.4-inch OLED', 'Various', '2227mAh', 'Dual 12MP Ultra Wide cameras', 'iOS 15');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(11, 'A15 Bionic', '6GB', '128GB/256GB/512GB', '6.1-inch OLED', 'Various', '3095mAh', 'Triple 12MP Ultra Wide cameras', 'iOS 15');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(12, 'A15 Bionic', '6GB', '128GB/256GB/512GB', '6.7-inch OLED', 'Various', '4352mAh', 'Triple 12MP Ultra Wide cameras', 'iOS 15');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(13, 'A14 Bionic', '4GB', '64GB/128GB/256GB', '6.1-inch OLED', 'Various', '2815mAh', 'Dual 12MP Ultra Wide cameras', 'iOS 14');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(14, 'A14 Bionic', '4GB', '64GB/128GB/256GB', '5.4-inch OLED', 'Various', '2227mAh', 'Dual 12MP Ultra Wide cameras', 'iOS 14');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(15, 'A14 Bionic', '6GB', '128GB/256GB/512GB', '6.1-inch OLED', 'Various', '2815mAh', 'Triple 12MP Ultra Wide cameras', 'iOS 14');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(16, 'A14 Bionic', '6GB', '128GB/256GB/512GB', '6.7-inch OLED', 'Various', '3687mAh', 'Triple 12MP Ultra Wide cameras', 'iOS 14');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(17, 'A13 Bionic', '4GB', '64GB/128GB/256GB', '6.1-inch LCD', 'Various', '3110mAh', 'Dual 12MP Ultra Wide cameras', 'iOS 13');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(18, 'A13 Bionic', '4GB', '64GB/256GB/512GB', '5.8-inch OLED', 'Various', '3046mAh', 'Triple 12MP Ultra Wide cameras', 'iOS 13');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(19, 'A13 Bionic', '4GB', '64GB/256GB/512GB', '6.5-inch OLED', 'Various', '3969mAh', 'Triple 12MP Ultra Wide cameras', 'iOS 13');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(20, 'A12 Bionic', '4GB', '64GB/256GB/512GB', '5.8-inch OLED', 'Various', '2658mAh', 'Dual 12MP Ultra Wide cameras', 'iOS 12');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(21, 'A12 Bionic', '4GB', '64GB/256GB/512GB', '6.5-inch OLED', 'Various', '3174mAh', 'Dual 12MP Ultra Wide cameras', 'iOS 12');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(22, 'A12 Bionic', '3GB', '64GB/128GB/256GB', '6.1-inch LCD', 'Various', '2942mAh', 'Single 12MP Wide camera', 'iOS 12');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(23, 'A11 Bionic', '3GB', '64GB/256GB', '5.8-inch OLED', 'Various', '2716mAh', 'Dual 12MP Ultra Wide cameras', 'iOS 11');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(24, 'Apple M1', '8GB/16GB', '256GB/512GB/1TB', '13.3-inch Retina', 'Various', 'Up to 18 hours', '720p FaceTime HD camera', 'macOS');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(25, 'Apple M2', '8GB/16GB', '256GB/512GB/1TB', '13.6-inch Liquid Retina', 'Various', 'Up to 18 hours', '1080p FaceTime HD camera', 'macOS');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(26, 'Apple M1', '8GB/16GB', '256GB/512GB/1TB', '13.3-inch Retina', 'Various', 'Up to 20 hours', '720p FaceTime HD camera', 'macOS');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(27, 'Apple M1 Pro', '8GB/16GB/32GB', '256GB/512GB/1TB/2TB/4TB', '14.2-inch Liquid Retina XDR', 'Various', 'Up to 17 hours', '1080p FaceTime HD camera', 'macOS');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(28, 'Apple M1 Pro', '16GB/32GB', '512GB/1TB/2TB/4TB', '16.2-inch Liquid Retina XDR', 'Various', 'Up to 21 hours', '1080p FaceTime HD camera', 'macOS');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(29, 'Apple M2', '8GB/16GB', '256GB/512GB/1TB', '13.3-inch Retina', 'Various', 'Up to 20 hours', '720p FaceTime HD camera', 'macOS');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(30, 'Apple M2 Pro', '16GB/32GB', '512GB/1TB/2TB/4TB', '14.2-inch Liquid Retina XDR', 'Various', 'Up to 17 hours', '1080p FaceTime HD camera', 'macOS');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(31, 'Apple M2 Pro', '16GB/32GB', '512GB/1TB/2TB/4TB', '16.2-inch Liquid Retina XDR', 'Various', 'Up to 21 hours', '1080p FaceTime HD camera', 'macOS');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(32, 'S8 SiP', 'N/A', '32GB', '49mm Retina display', 'Various', 'Up to 36 hours', 'N/A', 'N/A');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(33, 'S9 SiP', 'N/A', '32GB', '41mm or 45mm Retina', 'Various', 'Up to 18 hours', 'N/A', 'N/A');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(34, 'S8 SiP', 'N/A', '32GB', '41mm or 45mm Retina', 'Various', 'Up to 18 hours', 'N/A', 'N/A');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(35, 'S7 SiP', 'N/A', '32GB', '41mm or 45mm Retina', 'Various', 'Up to 18 hours', 'N/A', 'N/A');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(36, 'S6 SiP', 'N/A', '32GB', '41mm or 45mm Retina', 'Various', 'Up to 18 hours', 'N/A', 'N/A');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(37, 'S5 SiP', 'N/A', '32GB', '41mm or 45mm Retina', 'Various', 'Up to 18 hours', 'N/A', 'N/A');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(38, 'S5 SiP', 'N/A', '32GB', '41mm or 45mm Retina', 'Various', 'Up to 18 hours', 'N/A', 'N/A');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(39, 'W1 chip', 'N/A', 'N/A', 'N/A', 'White', 'Up to 5 hours of listening time', 'N/A', 'Bluetooth');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(40, 'H1 chip', 'N/A', 'N/A', 'N/A', 'White', 'Up to 5 hours of listening time', 'N/A', 'Bluetooth');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(41, 'H1 chip', 'N/A', 'N/A', 'N/A', 'White', 'Up to 6 hours of listening time', 'N/A', 'Bluetooth');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(42, 'H1 chip', 'N/A', 'N/A', 'N/A', 'White', 'Up to 4.5 hours of listening time', 'N/A', 'Bluetooth');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(43, 'H1 chip', 'N/A', 'N/A', 'N/A', 'White', 'TBA', 'N/A', 'Bluetooth');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(44, 'H1 chip', 'N/A', 'N/A', 'N/A', 'Various', 'Up to 20 hours of listening time', 'N/A', 'Bluetooth');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(45, 'Apple M1', '8GB/16GB', '128GB/256GB/512GB/1TB', '12.9-inch Liquid Retina XDR', 'Various', 'Up to 10 hours', '10MP Ultra Wide cameras', 'iPadOS');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(46, 'Apple M1', '8GB/16GB', '128GB/256GB/512GB/1TB', '11-inch Liquid Retina', 'Various', 'Up to 10 hours', '10MP Ultra Wide cameras', 'iPadOS');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(47, 'Apple A14 Bionic', '4GB', '64GB/256GB', '10.9-inch Liquid Retina', 'Various', 'Up to 10 hours', '12MP Wide camera', 'iPadOS');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(48, 'Apple A13 Bionic', '3GB', '64GB/256GB', '10.2-inch Retina', 'Various', 'Up to 10 hours', '8MP Wide camera', 'iPadOS');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(49, 'Apple A15 Bionic', '4GB', '64GB/256GB', '8.3-inch Liquid Retina', 'Various', 'Up to 10 hours', '12MP Wide camera', 'iPadOS');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(50, 'Apple M1', '8GB/16GB', '256GB/512GB/1TB', '24-inch 4.5K Retina', 'Various', 'N/A', '1080p FaceTime HD camera', 'macOS');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(51, 'Intel Core i5/i7/i9', '8GB/16GB/32GB/64GB', '256GB/512GB/1TB/2TB', '27-inch 5K Retina', 'Various', 'N/A', '1080p FaceTime HD camera', 'macOS');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(52, 'Apple M1', '8GB/16GB', '256GB/512GB/1TB/2TB', 'N/A', 'Various', 'N/A', 'N/A', 'macOS');
INSERT INTO appleDB.specification (product_id, processor, memory, storage, display, color, battery, camera, os) VALUES(53, 'N/A', 'N/A', 'N/A', '27-inch 5K Retina', 'Various', 'N/A', '1080p FaceTime HD camera', 'N/A');

INSERT INTO appleDB.review (product_id, reviewer, rating, comment) VALUES(1, '김민수', 5, '매우 만족합니다. 사용하기 편리하고 성능도 좋아요매우 만족합니다. 사용하기 편리하고 성능도 좋아요매우 만족합니다. 사용하기 편리하고 성능도 좋아요매우 만족합니다. 사용하기 편리하고 성능도 좋아요매우 만족합니다. 사용하기 편리하고 성능도 좋아요매우 만족합니다. 사용하기 편리하고 성능도 좋아요');
INSERT INTO appleDB.review (product_id, reviewer, rating, comment) VALUES(2, '이지은', 4, '디자인이 예쁘고 성능도 괜찮습니다. 가격이 조금 높은 감이 있지만 전반적으로 만족스러워요.');
INSERT INTO appleDB.review (product_id, reviewer, rating, comment) VALUES(3, '박준형', 3, '기대했던 것보다는 평범한 편이에요. 다음 모델은 개선이 필요할 것 같습니다.');
INSERT INTO appleDB.review (product_id, reviewer, rating, comment) VALUES(4, '최혜진', 5, '완벽한 제품입니다. 다른 제품과 비교해도 월등한 성능을 자랑합니다.');
INSERT INTO appleDB.review (product_id, reviewer, rating, comment) VALUES(5, '정태영', 2, '가격 대비 성능이 만족스럽지 않습니다. 다음에는 다른 제품을 고려해볼 생각입니다.');
INSERT INTO appleDB.review (product_id, reviewer, rating, comment) VALUES(6, '홍길동', 4, '일반적인 사용에는 충분히 좋은 성능을 보여줍니다. 가격 대비 만족도가 높습니다.');
INSERT INTO appleDB.review (product_id, reviewer, rating, comment) VALUES(7, '윤서아', 3, '기본적인 기능은 잘 작동하지만, 특별히 눈에 띄는 점은 없습니다. 중간 정도의 평가를 줍니다.');
INSERT INTO appleDB.review (product_id, reviewer, rating, comment) VALUES(8, '장민호', 4, '이 제품은 사용하기 쉽고 디자인도 멋집니다. 배터리 수명이 조금 더 길었으면 좋겠어요.');
INSERT INTO appleDB.review (product_id, reviewer, rating, comment) VALUES(9, '손흥민', 5, '성능이 뛰어나고 화면 해상도가 매우 인상적입니다. 게임이나 동영상 감상에 최적화된 제품이에요.');
INSERT INTO appleDB.review (product_id, reviewer, rating, comment) VALUES(10, '김예림', 3, '전반적으로 괜찮은 제품이지만, 가격 대비 기능이 조금 부족하다고 느꼈습니다. 가성비를 중시하는 사용자에게는 다른 옵션을 추천합니다.');
INSERT INTO appleDB.review (product_id, reviewer, rating, comment) VALUES(11, '이하늘', 2, '기대했던 것보다 성능이 낮고, 자주 오류가 발생합니다. 사용자 인터페이스도 다소 복잡한 편이에요.');
INSERT INTO appleDB.review (product_id, reviewer, rating, comment) VALUES(12, '박명수', 4, '매우 가볍고 휴대하기 편리합니다. 출장이나 여행 시에 아주 유용해요. 소리 질이 조금 더 좋았으면 하는 아쉬움이 있습니다.');
INSERT INTO appleDB.review (product_id, reviewer, rating, comment) VALUES(13, '유재석', 5, '디자인, 성능, 가격 모두 만족스럽습니다. 이 제품을 사용한 후로 다른 제품에는 눈길이 가지 않네요.');
INSERT INTO appleDB.review (product_id, reviewer, rating, comment) VALUES(1, '황지영', 4, '디자인이 심플하고 사용하기 편리해요. 하지만 약간의 업그레이드가 필요해 보입니다.');
INSERT INTO appleDB.review (product_id, reviewer, rating, comment) VALUES(2, '김태희', 5, '이 제품은 내 기대를 완벽하게 충족시켰습니다. 성능과 배터리 수명 모두 만족스러워요.');
INSERT INTO appleDB.review (product_id, reviewer, rating, comment) VALUES(3, '전지현', 3, '기본 기능은 좋지만, 가격이 조금 높다고 느꼈습니다. 좀 더 저렴했다면 좋았을 것 같아요.');
INSERT INTO appleDB.review (product_id, reviewer, rating, comment) VALUES(4, '류승범', 2, '기대했던 것보다 성능이 떨어지고, 자주 문제가 발생합니다. 기술 지원이 필요해 보여요.');
INSERT INTO appleDB.review (product_id, reviewer, rating, comment) VALUES(5, '이병헌', 4, '휴대성이 뛰어나고 사용하기 쉽습니다. 출장 갈 때 자주 사용하게 되네요.');
INSERT INTO appleDB.review (product_id, reviewer, rating, comment) VALUES(6, '정우성', 5, '이 제품은 탁월한 선택이었습니다. 성능과 가격 모두 만족스럽습니다.');
INSERT INTO appleDB.review (product_id, reviewer, rating, comment) VALUES(7, '송혜교', 3, '전반적으로 괜찮지만, 특정 기능에서는 개선이 필요해 보입니다.');
INSERT INTO appleDB.review (product_id, reviewer, rating, comment) VALUES(8, '강동원', 4, '매력적인 디자인과 우수한 성능을 가진 제품입니다. 사용자 경험이 매우 좋습니다.');
INSERT INTO appleDB.review (product_id, reviewer, rating, comment) VALUES(9, '손예진', 3, '일반적인 사용에는 적합하지만 고사양 작업에서는 다소 느리게 느껴집니다.');
INSERT INTO appleDB.review (product_id, reviewer, rating, comment) VALUES(10, '차승원', 2, '가격 대비 성능이 만족스럽지 않습니다. 다음 모델에서는 개선이 필요해 보여요.');
INSERT INTO appleDB.review (product_id, reviewer, rating, comment) VALUES(15, '이서진', 4, '사용하기 편리하고 성능도 좋습니다. 추천해요!');
INSERT INTO appleDB.review (product_id, reviewer, rating, comment) VALUES(16, '박나래', 5, '이 제품은 정말 훌륭합니다. 디자인과 성능 모두 만족스러워요.');
INSERT INTO appleDB.review (product_id, reviewer, rating, comment) VALUES(17, '이상민', 3, '기대했던 것보다는 평범한 편이에요. 가격 대비 성능이 조금 아쉬워요.');
INSERT INTO appleDB.review (product_id, reviewer, rating, comment) VALUES(18, '김종국', 2, '배터리 수명이 너무 짧아요. 개선이 필요합니다.');
INSERT INTO appleDB.review (product_id, reviewer, rating, comment) VALUES(19, '하하', 4, '전반적으로 만족스러운 제품입니다. 사용하기 쉽고 편리해요.');
INSERT INTO appleDB.review (product_id, reviewer, rating, comment) VALUES(20, '정준하', 5, '이 제품을 사용한 후 다른 제품은 사용할 수 없을 것 같아요. 완벽해요!');
INSERT INTO appleDB.review (product_id, reviewer, rating, comment) VALUES(21, '유재석', 3, '가격이 너무 높은 것 같아요. 하지만 성능은 좋습니다.');
INSERT INTO appleDB.review (product_id, reviewer, rating, comment) VALUES(22, '노홍철', 2, '때때로 오류가 발생해요. 안정성이 더 필요합니다.');
INSERT INTO appleDB.review (product_id, reviewer, rating, comment) VALUES(23, '정형돈', 4, '가격 대비 훌륭한 성능을 보여줍니다. 추천합니다.');
INSERT INTO appleDB.review (product_id, reviewer, rating, comment) VALUES(24, '길', 5, '디자인과 기능 모두 마음에 듭니다. 매우 만족스러워요.');
INSERT INTO appleDB.review (product_id, reviewer, rating, comment) VALUES(25, '조세호', 3, '기본적인 기능은 좋으나, 특별한 점은 없습니다.');
INSERT INTO appleDB.review (product_id, reviewer, rating, comment) VALUES(26, '양세형', 2, '가격이 너무 높아 가성비가 좋지 않습니다.');
INSERT INTO appleDB.review (product_id, reviewer, rating, comment) VALUES(27, '양세찬', 4, '사용하기 쉽고 휴대성이 좋습니다. 여행 시 유용해요.');
INSERT INTO appleDB.review (product_id, reviewer, rating, comment) VALUES(28, '지석진', 5, '매우 빠르고 효율적인 성능을 보여줍니다. 추천합니다.');
INSERT INTO appleDB.review (product_id, reviewer, rating, comment) VALUES(29, '김종민', 3, '사용하기에는 좋지만, 가격이 조금 부담스럽습니다.');
INSERT INTO appleDB.review (product_id, reviewer, rating, comment) VALUES(30, '이수근', 2, '기대했던 것보다 성능이 낮습니다. 다음 모델이 기대됩니다.');
INSERT INTO appleDB.review (product_id, reviewer, rating, comment) VALUES(31, '은지원', 4, '가벼움과 성능의 완벽한 조화를 보여줍니다.');
INSERT INTO appleDB.review (product_id, reviewer, rating, comment) VALUES(32, '강호동', 5, '성능, 디자인, 사용 편의성 모두 훌륭합니다.');
INSERT INTO appleDB.review (product_id, reviewer, rating, comment) VALUES(33, '신동엽', 3, '평범한 성능에 비해 가격이 높습니다. 가성비를 중시한다면 다른 옵션을 고려해보세요.');
INSERT INTO appleDB.review (product_id, reviewer, rating, comment) VALUES(34, '서장훈', 2, '기대보다 못 미치는 성능. 사용자 경험 개선이 필요해 보입니다.');